# Generated by Django 4.1.12 on 2023-11-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_tasks_remove_post_author_remove_post_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="priority",
            field=models.CharField(default="Low", max_length=20),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="image",
            field=models.ImageField(
                default="blog/images/coding.jpg", null=True, upload_to="posts"
            ),
        ),
    ]
