# Generated by Django 4.1.12 on 2023-11-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_tasks_priority_alter_tasks_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="priority",
            field=models.CharField(
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                default="Low",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
